name: Package and Release repository zip

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Version number for the release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      release-name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      prelease-notes:
        description: 'Release notes for the release'
        required: false
        default:  false
        type: boolean



jobs:
  create-package-release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip package
        id: zip-repository
        uses: thedoctor0/zip-release@0.7.6
        with:
          file-name: 'repository-package-${{ github.event.inputs.version }}.zip'
          exclusions: |
            .github/**
            **/*.yml
            **/*.yaml
            **/*.md
            **/node_modules/**
            **/tests/**

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
            tag: ${{ github.event.inputs['release-name'] }}
            name: ${{ github.event.inputs['tag-name'] }}
            body: |
                ## Release Notes
                ${{ github.event.inputs['prelease-notes'] }}
            draft: false
            prerelease: ${{ github.event.inputs['prelease-notes'] }}

 

  