name: Package and Release repository zip

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Version number for the release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      release-name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      pre-release:
        description: 'Is this a pre-release?'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  

jobs:
    
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create zip package
        id: create_zip
        run: |
            ZIP_FILE="repository-package-${{ github.event.inputs.tag-name }}.zip"
            git archive -o $ZIP_FILE HEAD
            echo "zip-file=$ZIP_FILE" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag-name }}
          release_name: ${{ github.event.inputs.release-name }}
          draft: false
          prerelease: ${{ github.event.inputs['pre-release'] }}
          body: "Release ${{ github.event.inputs.release-name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            

      

        
        
        
